#!/bin/sh
# Get IP address
cd /home/mcnvm1/host/
IP=$(ifconfig | awk -F':' '/inet addr/&&!/127.0.0.1/{split($2,_," ");print _[1]}')
echo "IP address is ${IP}"

case "$IP" in
   "10.0.0.1") ./MIMO_FUN_Terminal ./dumbbell/config_terminal_1.txt
   ;;
   "10.0.0.2") ./MIMO_FUN_Terminal ./dumbbell/config_terminal_2.txt
   ;;
   "10.0.0.3") ./MIMO_FUN_Terminal ./dumbbell/config_terminal_3.txt
   ;;
   "10.0.0.4") ./MIMO_FUN_Terminal ./dumbbell/config_terminal_4.txt
   ;;
   "10.0.0.5") ./MIMO_FUN_Edge ./dumbbell/config_edge_1.txt
   ;;
   "10.0.0.6") ./MIMO_FUN_Backbone ./dumbbell/config_backbone.txt
   ;;
   "10.0.0.7") ./MIMO_FUN_Edge ./dumbbell/config_edge_2.txt
   ;;
   *) echo "ERROR! Unidentified IP address in this scenario."
   ;;
esac
